const INITIAL_MASTER_DATA = [
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 75 - Sarri�-Sant Gervasi - Joan Bosco     PASSEIG JOAN BOSCO",
        "PROYECTO":  "SVO08036-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ALONSO ARTEMIO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 3 - Numancia - les corts",
        "PROYECTO":  "SVO05916-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "BETSAIDA MORENO ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 110 - Sardenya",
        "PROYECTO":  "SVO07732-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "BYRON GIOVANNY",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "LAURA FERNANDEZ ORTEGA  12/12",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 70 - Premia de mar",
        "PROYECTO":  "SVO08033-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "CRISTINA EXPOSITO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "baja de 3 dias",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA T12 - Igualada",
        "PROYECTO":  "SVO08181-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "DOROTEA JIMENEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "LAURA BONILLA",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 134 - Poblenou",
        "PROYECTO":  "SVO07461-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "EDUARDO GONZALEZ ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 87 - Guinardo",
        "PROYECTO":  "SVO05326-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "EVA MARIA CASERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "MONTSERRAT MARTINEZ",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "Se reincorpora 09/12 /2025",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 37 - Castelledefels",
        "PROYECTO":  "SVO08024-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "FRANCISCO CARPIO VILLANUEVA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "le faltan 3 dias vac  29-30-31 dic",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 31 - Vilafranca del Penedes",
        "PROYECTO":  "SVO08022-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "GABRIELA CONTRERAS PEREZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "titular nueva 05/12",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 109 - Granvia - Passeig de gracia",
        "PROYECTO":  "SVO05967-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "HECTOR ENRIQUEZ BONIFORTY QUINTERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "para enero",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 30 - Sant Joan despi",
        "PROYECTO":  "SVO05807-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "IVAN SIMARRO BLANCO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 89 - El Prat de llobregat",
        "PROYECTO":  "SVO08048-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "IZTIAR FERNANDEZ MARTINEZ",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "MOHAMED ARROUI 11/12",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 67 - Matar�",
        "PROYECTO":  "SVO08031-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JAMILA BENISS",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 103 -  Mila i Fontanals",
        "PROYECTO":  "SVO05919-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JOAQUIN GALADIES VILLA  ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "cambiar de ALDI",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 142 - Fortp�enc",
        "PROYECTO":  "SVO12043-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JOHON OSCAR ARNEZ ROJAS",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 28 - Esplugues",
        "PROYECTO":  "SVO05806-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JONATAN ANTUNES GRANADA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 11 - Viladecans",
        "PROYECTO":  "SVO08010-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JUAN MANUEL PLATA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "10/12 AL 2/01",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 96 - Sant Adri�- guipuscoa",
        "PROYECTO":  "SVO05328-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JUDITH BORBON VINAL",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "24/12 al 02/01",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 113 - Riera Alta",
        "PROYECTO":  "SVO05516-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "KEN ARNOL RIOS PINEDO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 78 - Sant Pere de Ribes",
        "PROYECTO":  "SVO08039-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "LIBERTAD",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "28354�",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 118 - Montcunill-la florida",
        "PROYECTO":  "SVO06275-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "LUIS ENRIQUE IZAGUIRRE COLMENARES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "baja de 1 dia",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 95 - Calella",
        "PROYECTO":  "SVO08053-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA CONCEPCION MARTINEZ CARRERAS",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "BEN CHERIF",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "01/12 AL 27/12",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 125 - Palleja",
        "PROYECTO":  "SVO10681-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA IBIZA RORODERA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 145-  Rosello",
        "PROYECTO":  "SVO10680-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA LUISA BRAVO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 77 - Passeig Maragall",
        "PROYECTO":  "SVO05329-P1-C018",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 13 -  Cabrera de Mar",
        "PROYECTO":  "SVO08012-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA PILAR ",
        "ESTADO1":  "",
        "FACT":  "A",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 40 - Sarri� - L\u0027eixample",
        "PROYECTO":  "SVO05917-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MERCEDES DOMINGO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "ENRIQUE SANCHEZ",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "16/12 al 31/12",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 123 - Fabra i Puig ( 4horas )",
        "PROYECTO":  "SVO05920-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MIGUEL FERNANDEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 10:30",
        "OBSERVACIONES":  "Se reincorpora 09/12 /2025",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 127 - Riera Blanca",
        "PROYECTO":  "SVO07458-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MIRIAM CORONAS MONELL",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 43 - Sitges",
        "PROYECTO":  "SVO08029-P1-C018",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "MIRIAM LUCERO AGUILAR HOYOS",
        "ESTADO1":  "VACACIONES",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 108 - Vilanova i la Geltr�  2",
        "PROYECTO":  "SVO08059-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "M� ISABEL LLOP",
        "ESTADO1":  "",
        "FACT":  "OK",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 85 - Gran Via-Tetuan",
        "PROYECTO":  "SVO05514-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MONTSERRAT GONZALEZ GOMEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 119  -Calle Bellver Barcelona",
        "PROYECTO":  "SVO07447-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MONTSERRAT MARTINEZ BERGA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 114 - Via Augusta",
        "PROYECTO":  "SVO07464-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MONTSERRAT NGOUNDO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 29 - Malgrat de Mar",
        "PROYECTO":  "SVO08020-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MONTSERRAT TURRO BA�OLAS",
        "ESTADO1":  "",
        "FACT":  "OK",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 92 - Badalona",
        "PROYECTO":  "SVO05921-P1-C018",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "NAIMA EL HIFD ",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 82 - Sants Pelegri  ( 4horas )",
        "PROYECTO":  "SVO05515-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "OLIVER CANETTI",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 10:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 128 - Cubelles",
        "PROYECTO":  "SVO08069-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "PEDRO GARCIA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 93 - Zona franca",
        "PROYECTO":  "SVO05637-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "RAFAEL HERNANDEZ PERALTA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 91 - Masquefa",
        "PROYECTO":  "SVO08049-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "RAQUEL MARTINEZ VALLADARES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 94 - Sepulveda",
        "PROYECTO":  "SVO05324-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "RITA GINER GALLEGO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "titular desde el 02/12",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 24 - Pineda de mar",
        "PROYECTO":  "SVO08017-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ROGER RODRIGUEZ GOMEZ",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "MARIA PILAR TURRO BA�OLAS",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 130 -  Ramba marina ",
        "PROYECTO":  "SVO07734-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ROMAN MARTINEZ CARRILLO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 73 - Sagrada familia ",
        "PROYECTO":  "SVO05323-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ROSA MARIA LOPEZ DIAZ",
        "ESTADO1":  "VACACIONES",
        "FACT":  "",
        "SUPLENTE":  "AARON 13/12",
        "HORARIO":  "L A V DE 6:30 A 10:30",
        "OBSERVACIONES":  "10/12 al 28/12",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 104 - Escorial",
        "PROYECTO":  "SVO05683-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "SAMANTA BELMONTE ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "JORDI DELGADO 17/12",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "Titular nueva",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 8 - Vilanova i la Geltr�  1",
        "PROYECTO":  "SVO08009-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "SANDRA TEJEDA CA�ADA ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 80 - Muntaner ",
        "PROYECTO":  "SVO05327-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "SERGIO MATEO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "es una baja corta",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 111 - El Masnou",
        "PROYECTO":  "SVO08061-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "SHAIKEL HAIDER",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 135 - Mercat de Montserrat",
        "PROYECTO":  "SVO12082-P1-C018 ",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "VICTOR PEREZ RICO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:30 A 9:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 86 - carrer Tallers 74  -castella",
        "PROYECTO":  "SVO05325-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "WISTON ALOMIA NU�EZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 7:30 A 11:30",
        "OBSERVACIONES":  "06:30 A 11:30 ",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ALDI",
        "SERVICIO":  "TIENDA 72 - El Born",
        "PROYECTO":  "SVO05322-P1-C018",
        "ESTADO":  "EN OBRAS",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "AGBAR",
        "SERVICIO":  "POLVOR�N MONTJU�C",
        "PROYECTO":  "SVO06796-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELECTRO",
        "SERVICIO":  "C/ Biscaia, 358-360-36   GRUPO ELECTRO STOCKS, S.L.",
        "PROYECTO":  "SVO02280-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELECTRO",
        "SERVICIO":  "Servicio Limpieza AV. EUROPA, 6  NAVE 1 GRUPO ELECTRO STOCKS, S.L",
        "PROYECTO":  "SVO02291-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELECTRO",
        "SERVICIO":  "P.I. S.ERMENGOL II, C/  GRUPO ELECTRO STOCKS, S.L",
        "PROYECTO":  "SVO02289-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELECTRO",
        "SERVICIO":  "P.I. SON ROSSINYOL, C/GRUPO ELECTRO STOCKS, S.L ",
        "PROYECTO":  "SVO02305-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "10:00 a 13:00",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "AICRAG",
        "SERVICIO":  "RECANVIS AICRAG, S.A.",
        "PROYECTO":  "PROY005696-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JUAN MANUEL PLATA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L , MIER , VIERNES DE 10:45 A 13:15",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELECTRO",
        "SERVICIO":  "CR PARELLADA 26-28 ( OLERDOLA )  Servicio Limpieza AV. EUROPA, 6  NAVE 1 GRUPO ELECTRO STOCKS, S.L",
        "PROYECTO":  "SVO10656-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELECTRO",
        "SERVICIO":  "AVENIDA PROGRES , 8 -  GRUPO ELECTRO STOCKS, S.L.",
        "PROYECTO":  "SVO02286-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "RESTO",
        "SERVICIO":  "(LIM) CC MAQUINISTA CRISTALES VARIOS CEN - MINISO LIFESTYLE SPAIN.SL",
        "PROYECTO":  "SVO06216-P1-C017",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "VEOLIA CRISTALES",
        "SERVICIO":  "(LIM) Mas Blau EL PRAT - ",
        "PROYECTO":  "SVO07555-P1-C018",
        "ESTADO":  "BRIGADA",
        "TITULAR":  "RUTA CRISTALES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ACCENTURE",
        "SERVICIO":  "LIMPIEZA PISOS VARIOS  ACCENTURE",
        "PROYECTO":  "PROY006411-P1 (T01)",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "BEATRIZ GARCIA ALBARCA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "JUEVES DE 10:30 A 12:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "AGBAR",
        "SERVICIO":  " C/ DOCTOR JOAQUIM PARELLADA,N�2 BAIXOS-LOCAL   (AVINYENT DEL PENEDES) ",
        "PROYECTO":  "SVO08188-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "GABRIELA CONTRERAS PEREZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "Martes de 10,30 a 11,30h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "AGBAR",
        "SERVICIO":  "OAC SITGES",
        "PROYECTO":  "SVO06921-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "\nPAULO RIBERA RODRIGUEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 13h a 14h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "AGBAR",
        "SERVICIO":  "OAC ARENYS DE MAR",
        "PROYECTO":  "SVO09515-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA CONCEPCION MARTINEZ CARRERAS",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "KHAJDIJA BEN CHERIF",
        "HORARIO":  "VIERNES de 13h a 14h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "AMERICOLD",
        "SERVICIO":  "Calle Pallars 103, planta 12 (BARCELONA )",
        "PROYECTO":  "SVO09676-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "M ANGELES SANCHEZ GOMEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 17 a 19h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ANIMUA",
        "SERVICIO":  "ANIMUA PLAZA URQUONA",
        "PROYECTO":  "",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ANNA IZQUIERDO POVEDANO",
        "ESTADO1":  "BAJA IT",
        "FACT":  "OLGA MARIA CALVO CASATEJADA ",
        "SUPLENTE":  "OLGA MARIA CALVO CASATEJADA ",
        "HORARIO":  "martes y jueves de 10:30 a 12:30",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ANIMUA",
        "SERVICIO":  "ANIMUA PRINCESA",
        "PROYECTO":  "SVO01045-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JUANA CORTES AMADOR",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L Mie y V de 9 a 12h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ANOREXIA",
        "SERVICIO":  "ASOC. CONTRA LA ANOREXIA",
        "PROYECTO":  "PROY017628-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "CECILIA QUINTANA FERNANDEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "Jueves de 11 a 14h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ASSOC DISCA",
        "SERVICIO":  "ASSOCIACIO DE DISCAPACITAT VISUAL  CAT",
        "PROYECTO":  "PROY008649-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA ASUNCION GARCIA ARRABAL",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L y Jueves de 9,30 a 11:30h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "Estaci� Renfe Gava, Carrer Salamanca, 1 - TRANSPORTES BLINDADOS",
        "PROYECTO":  "SVO06142-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "MARTES DE 8,30 A 10H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "Carrer d\u0027Isaac Peral, 0 (CORNELLA DEL LLOBREGAT) Trablisa Modulo Cornella  - TRANSPORTES BLINDADOS",
        "PROYECTO":  "SVO09276-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "Estaci� Renfe Castelldefels - Pla�a de l\u0027estaci�, s/n - TRANSPORTES BLINDADOS",
        "PROYECTO":  "SVO06141-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "MARTES DE 9,30 A 11H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "Estaci� Renfe Molins de Rei - Pla�a l\u0027Estaci�, 4  - TRANSPORTES BLINDADOS",
        "PROYECTO":  "SVO06138-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "MIERCOLES DE 11 A 12:30H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "Estaci� Renfe Vilanova y la Geltru - Pla�a d\u0027Eduard Maristan - TRANSPORTES B",
        "PROYECTO":  "SVO06140-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "VIERNES DE 11 A 12:30H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "Estaci� Renfe Martorell - Carrer Comer�, 1  - TRANSPORTES BLINDADOS",
        "PROYECTO":  "SVO06137-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "VIERNES DE 8 A 9,30H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "Estacio Renfe Vilafranca del Penedes -  Pla�a de l\u0027Estaci�, s/n - TRANSPORTES B",
        "PROYECTO":  "SVO06139-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "VIERNES DE 9:30 A 11H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "BLINDADOS",
        "SERVICIO":  "SEGUR DE CALAFELL",
        "PROYECTO":  "",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MATEO NU�EZ CAYERO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "VIERNES DE 9:30 A 11H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "EDAG CORNELLA",
        "SERVICIO":  "Crta. Del Prat 65, Pol. Almeda  EDAG ( CORNELLA )",
        "PROYECTO":  "PROY008589-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "EULALIA REY MARTIN",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 8 A 16H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "EDAG MARTORELL",
        "SERVICIO":  "EDAG MARTORELL",
        "PROYECTO":  "PROY008644-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "NIEVES REQUETA RULL ",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "NAJOUA EL MOUSSAOUI",
        "HORARIO":  "L A VIERNES DE 7 A 15H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "EDAG MARTORELL",
        "SERVICIO":  "EDAG MARTORELL",
        "PROYECTO":  "PROY008644-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ANA SANCHEZ BARRANCO ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A VIERNES DE 7 A 15H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "GES",
        "SERVICIO":  "P.I. CLOT DE MOJA. C/ GRUPO ELECTRO STOCKS, S.L      VILAFRANCA PENEDES",
        "PROYECTO":  "SVO02302-P2-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARI CARMEN POZO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "10 A 13H de martes y jueves",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELECTRO",
        "SERVICIO":  "Calle Miquel Biada, 2 ( CABRERA DE MAR )  - GRUPO ELECTRO STOCKS, S.L.",
        "PROYECTO":  "SVO08426-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JAMILA BENISS ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 10,30 A 12,30H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ELHIS",
        "SERVICIO":  "EHLIS, S.A. ( SANT ANDREU DE LA BARCA)",
        "PROYECTO":  "SVO03028-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JUAN ANTONIO SANTAMARINA REAL ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 7 a 15h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "EMETRES",
        "SERVICIO":  "INGENIEROS EMETRES SL",
        "PROYECTO":  "SVO04122-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ANDREU NICOLAU I MARTI ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "JUEVES 10:15 A 11:15",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "FICOSA",
        "SERVICIO":  "FICOSA",
        "PROYECTO":  "PROY011557-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "M ANGELES SANCHEZ GOMEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6 A 11H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "FUN LABORAL CONS",
        "SERVICIO":  "Avinguda de la Comunitat Europea, 32 ( BADALONA )",
        "PROYECTO":  "SVO05000-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MILAGROSA NSUE NDONG",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "Lunes a viernes de 7h a 11h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "FILANTROPICO",
        "SERVICIO":  "Cafeteras Technip - FILANTROPICO",
        "PROYECTO":  "SVO07831-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ERNESTO PEREZ VILARRUBIAS ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 7 a 8h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "GAM",
        "SERVICIO":  "SERVICIOS DE MAQUINARIA,  ( MOLINS DE REI )",
        "PROYECTO":  "SVO04868-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ROBERTO ARRIBA IGLESIAS",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 8 A 13H Y DE 15 A 18H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "GESTIN",
        "SERVICIO":  "limpieza CP Ramon de Penyafort, 11 Sta M  - GESTIN S.A.P",
        "PROYECTO":  "PROY018417-P2-C001",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "ANA MARIA PEREZ PRAT",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "FALTA SUPLENTE",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "HANES",
        "SERVICIO":  "C/LLACUNA, 56-70 ED.A 3� PLANTA dim (BARCELONA) HANES COMMERCIAL - Commercial Europe SARL/Spanish Branc",
        "PROYECTO":  "PROY018537-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "SONNIA MARIA RECALDE FRANCO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 18 a 22h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "GAS N2TROGEN",
        "SERVICIO":  "GAS N2ITROGEN, SL",
        "PROYECTO":  "SVO06264-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ISABEL PONCE BARCIA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 8 A 12H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "HEMISPEHRE",
        "SERVICIO":  "HEMISPHERE COATING SERVICES SL.  PINMAR",
        "PROYECTO":  "SVO01692-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "RINELDA JULIA RODRIGUEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 17 A 21H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "HEMISPEHRE",
        "SERVICIO":  "HEMISPHERE COATING SERVICES SL.  PINMAR",
        "PROYECTO":  "SVO01692-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA CRISTINA JARAMILLO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 17 A 21H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "HEMISPEHRE",
        "SERVICIO":  "HEMISPHERE COATING SERVICES SL.  PINMAR",
        "PROYECTO":  "SVO01692-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "CORALICIA SIERRA CHAVEZ",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "ANA MILENA ",
        "HORARIO":  "L A V DE 17 A 21H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "idom cornella",
        "SERVICIO":  "IDOM BARCELONA CORNELLA",
        "PROYECTO":  "PROY008594-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MIRTA RAQUEL ARRETCHE FERNANDEZ",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "NO SE CUBRE ",
        "HORARIO":  "L A V 12:30 A 16H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "idom cornella",
        "SERVICIO":  "IDOM BARCELONA CORNELLA",
        "PROYECTO":  "PROY008594-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JUANA MARIA VERA LUCAS",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V 6 A 9:30H   Y DE 12:30 A 16H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "idom cornella",
        "SERVICIO":  "IDOM BARCELONA CORNELLA",
        "PROYECTO":  "PROY008594-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "EVELYN ROXANA GARCIA FIGUEROA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V 6 A 9:30H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "IM3",
        "SERVICIO":  "Pau Claris, 165, 1� Planta ( MOLINS DE REI) - IM3 ",
        "PROYECTO":  "PROY014376-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MARIA IBIZA RORODERA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L , MI Y VIERNES DE 13 A 15H",
        "OBSERVACIONES":  "16/03 al 22/03   y ",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "IM3",
        "SERVICIO":  "IM3,  Pau Claris, 165, 1� Planta (BARCELONA ) - INGENIEROS EMETRES SL",
        "PROYECTO":  "PROY010078-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "FREDDY JULIAN GONZALEZ SILVA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V 6 a 8h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "INNOIT",
        "SERVICIO":  "Diputaci�n, 280 Pt1 - 2 (BARCELONA)  -  INNOIT CONSULTING S.L.",
        "PROYECTO":  "SVO06768-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "LUCIA PRIETO GONZALEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 7 A 10H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "INNOIT",
        "SERVICIO":  "Diputaci�n, 280 Pt1 - 2 (BARCELONA)  -  INNOIT CONSULTING S.L.",
        "PROYECTO":  "SVO06768-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ANDREU NICOLAU I MARTI ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 14 a 15h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "MEDIAMARTKET",
        "SERVICIO":  "MEDIA MARKT EL PRAT/CORNELL�",
        "PROYECTO":  "SVO05455-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "LUZ DEL CARMEN PEREZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a V de 17 a 19h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "MEDIAMARTKET",
        "SERVICIO":  "MEDIA MARKT EL PRAT/CORNELL�",
        "PROYECTO":  "SVO05455-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "DANIEL DURAN CASTA�O",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 8:00 A 12:30  Y SAB 8 A 12,30H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "OBRES I SERVEIS ",
        "SERVICIO":  "Av. de Torrelles, 16 ( SANT VI�ENS DELS HORTS )",
        "PROYECTO":  "SVO08168-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ROSA MARIA LOZANO FERNANDEZ",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "CRISTINA SALGADO ",
        "HORARIO":  "L Mie y V de 8 a 13h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "PUMA",
        "SERVICIO":  "PLAZA DE LA PAU S/N WTC ALMEDA PARC EDIF.2 BAJOS",
        "PROYECTO":  "PROY011521-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MANUEL REYES",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A VIERNES DE 6 A 11H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "PUMA",
        "SERVICIO":  "PLAZA DE LA PAU S/N WTC ALMEDA PARC EDIF.2 BAJOS",
        "PROYECTO":  "PROY011521-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ANA NAVARRO PALMA",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "EMERGENCIAS",
        "HORARIO":  "L A JUEVES DE 13 A 17H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "QUINERA",
        "SERVICIO":  "Carrer de la Mare de D�u del Coll, 70 LOCAL ( BARCELONA) - Qinera BJ S.C.C.L",
        "PROYECTO":  "SVO06102-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "CARMEN RUIZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L a Jueves de 6 a 9h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "RESTO",
        "SERVICIO":  "C.P ARIBAU 259  - CONSERJERIA",
        "PROYECTO":  "SVO10689-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "LIDIA CUBILLAS LUQUE",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "VICTOR SOBRINO",
        "HORARIO":  "L a V de 9 a 14h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "RIING",
        "SERVICIO":  "Estaci�n de recarga el�ctricaGarraf. C-32 -41�13\u002716. ( CUBELLES )   RIING",
        "PROYECTO":  "SVO10359-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "PERE QUELART VENTURA",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "MARTES DE 15 A 18H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "SEMYDINAMICS",
        "SERVICIO":  "Avenida Josep Tarradellas 20 . planta 1 y 3-(BARCELONA ) ",
        "PROYECTO":  "SVO08603-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "SUSANA MARTINEZ FERNANDEZ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "Lunes a viernes de 16h a 21h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "SEMYDINAMICS",
        "SERVICIO":  "Avenida Josep Tarradellas 20 . planta 1 y 3-(BARCELONA ) ",
        "PROYECTO":  "SVO08603-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "DANITZA VICTORIA ORTIZ ARANCIBIA ",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "Lunes a viernes de  7h a 12h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "UNISONO",
        "SERVICIO":  "UNISONO BARCELONA",
        "PROYECTO":  "PROY014012-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "MONICA CALLADO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L A V DE 6:20 a 9,30h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "UNISONO",
        "SERVICIO":  "UNISONO BARCELONA",
        "PROYECTO":  "PROY014012-P1",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "JUDIT COLOME",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "DE LUNES A VIERNES DE 6 A 9:30 Y DE 16 A 18  DOMINGOS 6 A 11",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "UNISONO",
        "SERVICIO":  "UNISONO BARCELONA",
        "PROYECTO":  "PROY014012-P2-C001",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "ELIAS GONZALEZ GARCIA",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "SIDI AHMED BOUHADI",
        "HORARIO":  "L A V DE 6 A 10H   y sab d 6 a 13h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "VEOLIA",
        "SERVICIO":  "CETAQUA ( SANT JOAN DESPI )",
        "PROYECTO":  "SVO08233-P1-C018",
        "ESTADO":  "CUBIERTO",
        "TITULAR":  "IVAN SIMARRO BLANCO",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "L Mie  de 16:30 a 18:30  y Viernes de 15 a 17",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  "SVO09531"
    },
    {
        "TIPO S":  "VEOLIA",
        "SERVICIO":  "OFICINA Y ALMAC�N CUZCO",
        "PROYECTO":  "SVO08186-P1-C018",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "MARIA DOLORES SANCHEZ POYATO",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "LUCIA PE�A",
        "HORARIO":  "Martes y jueves de 09:00 a 11:45 ",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "ANIMUA",
        "SERVICIO":  "ANIMUA PLAZA URQUONA",
        "PROYECTO":  "SVO01045-P2-C001",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "ANNA IZQUIERDO POVEDANO",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "OLGA MARIA CALVO CASATEJADA ",
        "HORARIO":  "Martes   09:30 a 12:30  y jueves de 09:30 a 11:30 ",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "PUMA",
        "SERVICIO":  "PLAZA DE LA PAU S/N WTC ALMEDA PARC EDIF.2 BAJOS",
        "PROYECTO":  "PROY011521-P2-C002",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "AGUSTINA PICON GOMIS",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "MONTSERRAT BAENA GRIMA",
        "HORARIO":  "L A VIERNES DE 6 A 11H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "QUINERA",
        "SERVICIO":  "Carrer de la Mare de D�u del Coll, 70 LOCAL ( BARCELONA) - Qinera BJ S.C.C.L",
        "PROYECTO":  "SVO06102-P1-C018",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "JOSE LUIS LOPEZ YEBRA",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "EMERGENCIAS",
        "HORARIO":  "L a Jueves de 6 a 9h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "TINTORE",
        "SERVICIO":  "CONSTRUCCIONES MEC TINTORE SA",
        "PROYECTO":  "SVO00999-P1-C001",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "ANNA IZQUIERDO POVEDANO",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "OLGA MARIA CALVO CASATEJADA ",
        "HORARIO":  "L Mie y V de 6 A 11H",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "VEOLIA",
        "SERVICIO":  "OAC CUBELLES",
        "PROYECTO":  "SVO08195-P1-C018",
        "ESTADO":  "DESCUBIERTO",
        "TITULAR":  "AITOR RUIS VERA",
        "ESTADO1":  "BAJA IT",
        "FACT":  "",
        "SUPLENTE":  "EMERGENCIAS",
        "HORARIO":  "L a Jueves de 7:30 a 10h y viernes 7:30 a 9:30h",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "",
        "SERVICIO":  "",
        "PROYECTO":  "",
        "ESTADO":  "",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "",
        "SERVICIO":  "",
        "PROYECTO":  "",
        "ESTADO":  "",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "",
        "SERVICIO":  "",
        "PROYECTO":  "",
        "ESTADO":  "",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "",
        "SERVICIO":  "",
        "PROYECTO":  "",
        "ESTADO":  "",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "",
        "SERVICIO":  "",
        "PROYECTO":  "",
        "ESTADO":  "",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "",
        "SERVICIO":  "",
        "PROYECTO":  "",
        "ESTADO":  "",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    },
    {
        "TIPO S":  "",
        "SERVICIO":  "",
        "PROYECTO":  "",
        "ESTADO":  "",
        "TITULAR":  "",
        "ESTADO1":  "",
        "FACT":  "",
        "SUPLENTE":  "",
        "HORARIO":  "",
        "OBSERVACIONES":  "",
        "VACACIONES 26":  ""
    }
];